apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: website-resource-manager
rules:
- apiGroups: ["","apps","extensions.example.com"] # "" indicates the core API group
  resources: ["pods","services","deployments","websites"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: website-resource-manager-binding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: website-resource-manager
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: website-controller
  namespace: default